apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://neo4j.com/docs/operations-manual/current/kubernetes/helm-charts-setup/

helmCharts:
- name: neo4j
  repo: https://helm.neo4j.com/neo4j
  version: 5.15.0
  releaseName: neo4j
  namespace: graph-system
  valuesFile: values.yaml
