apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-frontend
  template:
    metadata:
      labels:
        app: graph-frontend
    spec:
      containers:
      - name: nginx
        image: quay.io/myorg/graph-frontend:latest
        ports:
        - containerPort: 8080
      - name: oauth-proxy
        image: quay.io/openshift/origin-oauth-proxy:latest
        args:
          - --provider=openshift
          - --https-address=:8443
          - --upstream=http://localhost:8080
          - --client-id=graph-frontend
          - --client-secret=$(CLIENT_SECRET)
          - --cookie-secret=$(COOKIE_SECRET)
          - --email-domain=*
          - --scope=user:info user:check-access
          - --openshift-sar={"resource":"pods","verb":"get"}
        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-proxy-secrets
              key: client-secret
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-proxy-secrets
              key: cookie-secret
        ports:
        - containerPort: 8443
