apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-stack
spec:
  project: default
  source:
    repoURL: https://github.com/myorg/graph-visualisation
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: graph-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
