apiVersion: batch/v1
kind: CronJob
metadata:
  name: jira-etl
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: jira-etl
            image: quay.io/myorg/jira-etl:latest
            env:
            - name: JIRA_URL
              valueFrom:
                secretKeyRef:
                  name: jira-credentials
                  key: url
            - name: JIRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jira-credentials
                  key: username
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jira-credentials
                  key: api-token
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: etl-config
                  key: neo4j-uri
            - name: NEO4J_USER
              valueFrom:
                configMapKeyRef:
                  name: etl-config
                  key: neo4j-user
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: password
            - name: JIRA_PROJECTS
              value: "AAP,PLATFORM,DEVOPS"  # Comma-separated list of project keys
            volumeMounts:
            - name: etl-config
              mountPath: /app/config
              readOnly: true
          volumes:
          - name: etl-config
            configMap:
              name: etl-config
